-- phpMyAdmin SQL Dump
-- version 4.4.12
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: 2015 年 9 月 26 日 16:19
-- サーバのバージョン： 5.6.25
-- PHP Version: 5.6.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ibarucky`
--

-- --------------------------------------------------------

--
-- テーブルの構造 `news`
--

CREATE TABLE IF NOT EXISTS `news` (
  `news_id` int(11) NOT NULL,
  `news_title` varchar(64) NOT NULL,
  `news_detail` varchar(4096) NOT NULL,
  `show_flg` int(11) NOT NULL,
  `author` varchar(12) NOT NULL,
  `news_url` varchar(255) NOT NULL,
  `news_cat` int(11) NOT NULL,
  `create_date` datetime NOT NULL,
  `update_date` datetime NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

--
-- テーブルのデータのダンプ `news`
--

INSERT INTO `news` (`news_id`, `news_title`, `news_detail`, `show_flg`, `author`, `news_url`, `news_cat`, `create_date`, `update_date`) VALUES
(1, '筑波宇宙センター/つくば市', '&lt;p&gt;筑波宇宙センターは筑波研究学園都市の一画にあり、1972（昭和47）年に開設。&lt;/p&gt;\r\n&lt;p&gt;約53万平方メートルの敷地に、研究学園都市にふさわしい緑ゆたかな環境と最新の試験設備を備えた総合的な事業所です。&lt;/p&gt;\r\n&lt;p&gt;このセンターは、人工衛星やロケットなど将来の宇宙機の研究開発や開発試験、そして打ち上げた人工衛星を追跡管制する、日本のネットワークの拠点として重要な役割を担っています。&lt;/p&gt;\r\n&lt;p&gt;さらに国際宇宙ステーション計画に向けた「きぼう」日本実験棟の開発や試験、宇宙飛行士の養成などを行っています。&lt;/p&gt;\r\n&lt;p&gt;アクセス：JR 常磐線　荒川沖駅　&lt;/p&gt;\r\n&lt;p&gt;タクシー： 約 15 分 つくばエクスプレス線　つくば駅　&lt;/p&gt;\r\n&lt;p&gt;タクシー：約 10 分 常磐自動車道　桜土浦インターから約 7 分&lt;/p&gt;', 1, '管理者', '宇宙センター.jpg', 2, '2015-09-06 17:18:21', '2015-09-26 19:14:19'),
(2, '歴史館の銀杏並木', '&lt;p&gt;まさにこれから見頃を迎えるいちょう並木。&lt;/p&gt;\r\n&lt;p&gt;茨城県でいちょう並木を楽しみたいなら絶対に行くべきスポットが水戸市にある「歴史館の銀杏並木」。&lt;br /&gt;&lt;br /&gt;夜にはいちょう並木がライトアップされ、ロマンチックなムードが漂います。彼氏や彼女とのデートにもいいかも♪&lt;/p&gt;', 1, '管理者', 'item02.jpg', 8, '2015-09-06 17:58:31', '2015-09-26 19:21:14'),
(3, '土浦全国花火競技大会', '&lt;p&gt;秋田県大曲の花火大会、新潟長岡まつりの花火大会と並び&amp;ldquo;日本三大花火大会&amp;rdquo;と称されるほど有名な「土浦全国花火競技大会」！&lt;br /&gt;こんな大きな花火大会が茨城にはあるんですよ！&lt;br /&gt;&lt;br /&gt;腕に自身のある花火技師が多く集まるため、その迫力と美しさは全国トップレベル。2万発以上もの花火が打ち上げられ、毎年50万人以上の人が見に訪れるのだそう♪&lt;/p&gt;', 1, '管理者', 'item03.jpg', 2, '2015-09-09 19:51:24', '2015-09-26 19:22:48'),
(4, 'しし鍋', '&lt;p&gt;茨城県内で猪肉の出荷が許可されている石岡市で食べられるしし鍋。&lt;br /&gt;歯ごたえがあり、低脂肪でヘルシーなのが猪肉の特徴。&lt;br /&gt;さっぱりとしているので、食べやすいです。&lt;br /&gt;狩猟期は、だいたい１１〜３月なので、その時期に旅行を計画している方は、是非味わってみてください。&lt;/p&gt;', 1, '管理者', 'rankingshare-4b94a4b0226911e3af1a00007f000001c5aec1da12dd5a2e13.jpg', 7, '2015-09-09 19:53:01', '2015-09-26 19:26:18'),
(5, 'けんちんうどん・そば', '&lt;p&gt;大子町の名物料理「けんちんうどん」。&lt;br /&gt;牛蒡、人参、こんにゃく、大根、豆腐などが入った汁に、うどんをつけて食べるつけ麺スタイルが主流。&lt;br /&gt;また、「けんちんそば」も人気です。&lt;br /&gt;けんちん汁は、もともと精進料理だったそうで、それに蕎麦やうどんをつけて食べるスタイルが奥久慈大子町で流行ったんだそうです。&lt;/p&gt;', 1, '管理者', 'rankingshare-b53c6a00226a11e390d400007f0000012e1fc530fc0bda14d2.jpg', 7, '2015-09-09 19:53:51', '2015-09-26 22:24:55'),
(6, '行方丼', '&lt;p&gt;行方市が推奨しているプロジェクトから生まれた「行方丼（なめがたどん）」。&lt;br /&gt;霞ヶ浦で採れるナマズ、シラウオ、川エビ、鯉などを唐揚げや天ぷらなどにし、ご飯に乗せます。&lt;br /&gt;行方丼の加盟店が市内にたくさんありますが、お店によって具材も様々なので、最初に下調べして行くのも手かも♪。&lt;/p&gt;', 1, '管理者', 'rankingshare-fb141810226b11e397a100007f0000014aab322002ccfd5b0b.jpg', 7, '2015-09-12 09:46:35', '2015-09-26 22:25:58'),
(7, 'ワープステーション江戸/つくばみらい市', '&lt;p&gt;JIN-仁・永遠の0・るろうに剣心・ゲゲゲの女房や大河ドラマ「江」・龍馬伝など、数々の映像作品のロケ地となっているワープステーション江戸。&lt;br /&gt; 江戸城ゾーンや町屋などはもちろん、江戸時代だけではなく昭和初期のセットも立ち並んでいます。&lt;br /&gt; 作品に合わせて時代背景の模様替えもするので行く度に違う時代にタイムスリップできちゃいます♪&lt;br /&gt; 公開料：大人400円　子供200円&lt;br /&gt; 毎週月曜日（月曜日が祝日の場合は翌日）&lt;br /&gt; アクセス：つくばエクスプレス　みらい平駅より車で10分&lt;br /&gt; 常磐自動車道矢田部I.Cから約10分&lt;/p&gt;', 1, '', 'slide03.jpg', 5, '2015-09-19 15:51:08', '2015-09-26 19:06:53'),
(8, '竜神大吊橋/常陸太田市', '&lt;p&gt;竜神峡は茨城県の奥久慈県立自然公園に位置します。竜神峡にひろがるV字形の美しい渓谷の中を流れる竜神川をせき止めた竜神ダムの上に竜神大吊橋はかけられました。&lt;br /&gt; 橋の長さは375mあり、歩行者専用の橋としては本州一の長さを誇ります。&lt;br /&gt; ダム湖面よりの高さは100m、橋の上からの眺めは絶景で、四季おりおりのパノラマが広がります。橋の両側にある壁面には山と大地をイメージした絵が描かれており、&lt;br /&gt; 橋はその大自然の空間を舞い上がる竜を想起させます。&lt;br /&gt; 渡橋料金：大人310円　子供210円&lt;br /&gt; アクセス：常磐自動車道・那珂ICから国道349号を経由し竜神大吊橋方面へ&lt;br /&gt; JR常磐線・水戸駅乗り換え、JR水郡線・常陸太田駅下車。&lt;/p&gt;', 1, '', '竜神大吊橋.jpg', 2, '2015-09-20 21:47:24', '2015-09-26 19:10:25'),
(9, '竜神大吊橋バンジー/常陸太田市', '&lt;p&gt;高さ最大100メートルとなる竜神バンジーは、シーズン常設開催サイトとして日本最大級となります。&lt;br /&gt; 竜の形をした湖上に架かる、歩行者専用の橋として本州一である竜神大吊橋は全長375メートル！&lt;br /&gt; それだけで存在感あふれる景観をつくりだし、毎年何万人もの観光客を魅了している大人気の観光スポットです。&lt;br /&gt; 四季折々姿を変える圧巻の絶景を臨み、湖面に向かってジャンプします。何十回と飛んでいるバンジーファンの方や、高い場所を得意とするバンジーのスタッフでさえ&lt;br /&gt; 「想像以上のスリル」と口を揃えてコメントするほど！竜神バンジーではウインチ方式を採用します。元来バンジージャンプではジャンプしたあとは下に降りますが、&lt;br /&gt; ここでは電動ウインチによって、橋の上に引き上げられます。ジャンプ後はすぐに上に戻り、皆で感動を分かち合えますよ♪&lt;br /&gt; 料金：1回目-14,000円 ・同日2回目 &amp;ndash; 6,000円・2回目以降 &amp;ndash; 9,000円（要認定書＆身分証明書）&lt;br /&gt; みなかみ又は猿ヶ京バンジーに参加された事がある方-13,000円 （要認定書＆身分証明書）&lt;br /&gt; アクセス：常磐自動車道・那珂ICから国道349号を経由し竜神大吊橋方面へ&lt;br /&gt; JR常磐線・水戸駅乗り換え、JR水郡線・常陸太田駅下車。&lt;/p&gt;', 1, '', 'バンジージャンプ.jpg', 1, '2015-09-20 21:50:38', '2015-09-26 19:11:15'),
(10, '出雲大社/笠間市', '&lt;p&gt;平成4年12月4日、御本社出雲大社（島根県・大社町）より御分霊を御鎮座。「日本文徳天皇実録」（871年）によると御祭神大国主大神は、神代の昔、常世之国（常陸国・現在の茨城県）の少名彦命と共に国づくりに&lt;br /&gt; 励まれたと伝えられています。&lt;br /&gt; アクセス：JR水戸線　福原駅下車　徒歩7分&lt;br /&gt; 北関東自動車道笠間方面&amp;rarr;笠間西I.C下車1km&lt;/p&gt;', 1, '', '出雲大社.jpg', 1, '2015-09-20 21:51:21', '2015-09-26 19:11:45'),
(11, '袋田の滝/大子町', '&lt;p&gt;日本の滝百選の人気投票では1位を取ったこともある、茨城県久慈郡大子町袋田にある滝。久慈川支流の滝川上流にあたり、長さ120m、幅73m。&lt;br /&gt; 冬は「氷瀑」と呼ばれる、滝が凍結する現象が発生することがあるんです。マイナスイオンたっぷりの空気が漂っていて癒されスポットへ足を運んでみませんか♪&lt;br /&gt; アクセス：常磐自動車道「那珂IC」より約50分&lt;br /&gt; JR水郡線「袋田駅」よりバスで10分&lt;/p&gt;', 1, '', '袋田の滝.jpg', 2, '2015-09-20 22:17:59', '2015-09-26 22:47:08'),
(12, 'ひたち海浜公園(ひたちなか市)', '&lt;p&gt;茨城県ひたちなか市にある日本の国営公園。ROCK IN JAPAN FESTIVALの開催地でもあり、その時には東京&lt;br /&gt; ディズニーランドの5倍もある広大な敷地を借切って行われています。遊園地やサイクリングロード、バーベキュー&lt;br /&gt; 施設もあり、1日中いろんな遊び方で楽しむことができます！小さなお子様連れにもおすすめ度満点です！！&lt;br /&gt; 入園料：大人400円　子供80円&lt;br /&gt; 休園日：毎週月曜日（祝日の場合はよく火曜日）&lt;br /&gt; アクセス：北関東自動車道～常陸那珂有料道路　ひたち海浜公園ICより約1km&lt;br /&gt; 常磐自動車道をご利用の場合　日立南太田ICより約15km&lt;br /&gt; JR常磐線　勝田駅からタクシーで約15分&lt;/p&gt;', 1, '', '海浜公園.jpg', 1, '2015-09-26 19:05:27', '2015-09-26 22:27:12'),
(13, '月待の滝（久慈郡）', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;この珍しい形状のためか、古くから安産、子育て、開運を祈る二十三夜講（二十三夜の月の出を待って婦女子が集う）の場とされたところから月待の滝と呼ばれ、胎内観音をお祀りしています。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.daigo-kanko.jp/?page_id=2861&quot; target=&quot;_blank&quot;&gt;www.daigo-kanko.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;ドラマ『ガラスの仮面』の舞台ともなっている「月待の滝」！月待の滝は、通常は二筋の夫婦滝であるが、水量が多い場合には三筋の親子滝になることもあるの だそう♪ 滝の裏側にも濡れることなく入っていけるそうなので、訪れた際にはぜひ滝の裏側まで行ってみてください。&lt;/div&gt;', 1, '', '234602086888-0c26-46f7-a763-eb791a4d93c3_m.jpg', 2, '2015-09-26 22:28:32', '2015-09-26 22:28:32'),
(14, '大洗水族館（東茨城郡）', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;日本一のサメの飼育数を誇り、マンボウやラッコなど約580種68000点の世界の海の生物に出会うことができる&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.ibarakiguide.jp/db-kanko/aquaworld.html&quot; target=&quot;_blank&quot;&gt;www.ibarakiguide.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;日本トップクラスであり、関東最大規模の水族館である「大洗水族館」。50種以上のサメを飼育しているのだというから驚き・・・！茨城を訪れた際には訪れておきたい人気観光スポット♪&lt;/div&gt;', 1, '', '23468dc81e97-d171-4d31-92b8-bcf9447d7087_m.jpg', 2, '2015-09-26 22:29:34', '2015-09-26 22:29:34'),
(15, '筑波海軍航空隊記念館（笠間市）', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;茨城県笠間市にあった旧海軍基地、『筑波海軍航空隊』は『永遠の0』の主人公・宮部久蔵（岡田准一）が教官として勤務していたという設定の地です。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.p-ibaraki.com/tsukuba&quot; target=&quot;_blank&quot;&gt;www.p-ibaraki.com&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;大ヒット映画「永遠の０」のロケ地が、実は茨城県にあったことを知っている人は少ないのではないでしょうか。&lt;br /&gt;国内最大級で現存する戦争遺構である「筑波海軍航空隊記念館」。隊員たちの生き様を知ることができ、実際に戦争が起きていたという事実を実感することのできる場所です。&lt;/div&gt;', 1, '', '2346851e7b67-463f-4d29-815b-40c5f14d78c5_m.jpg', 8, '2015-09-26 22:35:12', '2015-09-26 22:35:12'),
(16, '福岡堰（つくばみらい市）', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;現在の福岡堰は昭和47年に完成したもので、岡堰、豊田堰とともに関東三大堰の一つに数えられます。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.city.tsukubamirai.lg.jp/bunka/08.htm&quot; target=&quot;_blank&quot;&gt;www.city.tsukubamirai.lg.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;春になると、約550本のソメイヨシノが咲き誇る福岡堰。その美しさから、茨城観光百選にも選ばれているのだそう♪ 「桜まつり」が行われている期間には、県外からも多くの人が桜を眺めにくるほど桜の美しいようです！&lt;/div&gt;', 1, '', '2346b352ec3a-3e18-4fc1-b758-912ce2ac1d71_m.jpg', 8, '2015-09-26 22:35:50', '2015-09-26 22:35:50'),
(17, '鹿島神宮', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;鹿島神宮は、常陸国（茨城県）の一宮。約600社ある鹿島神社の総本社で、関東最古の神社です。香取神宮とペアで関東の東を護っています。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://jin-power.com/modules/todoufuken/index.php?content_id=66&quot; target=&quot;_blank&quot;&gt;jin-power.com&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;パワースポット巡りがだいすきなあなたにオススメの場所が「鹿島神宮」。強力な海運パワーのある神社です！人生を転換するターニングポイントの作用をもっているのだそう。行ってみたい！！！&lt;/div&gt;', 1, '', '2346ad2b7eb3-3b5b-45a8-aad0-91328baa1969_m.jpg', 2, '2015-09-26 22:36:40', '2015-09-26 22:36:40'),
(18, '霞ヶ浦　帆引き船', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;霞ヶ浦の風物詩である帆引き船は、本市に生まれた折本良平氏によって考案され、明治13年に初めて霞ヶ浦に浮かびました。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.city.kasumigaura.ibaraki.jp/?page_id=487&quot; target=&quot;_blank&quot;&gt;www.city.kasumigaura.ibaraki.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;毎年7月下旬から11月下旬の日曜日に行われている茨城県霞ヶ浦の「観光帆引き船」。白く大きい帆をあげ、のんびりと走る姿をみてみたいものですね♪&lt;/div&gt;', 1, '', '2346cf74d1f5-6ff4-4ce2-ae66-c08fd07b4aaa_m.jpg', 8, '2015-09-26 22:38:24', '2015-09-26 22:38:24'),
(19, '峰寺山西光院（石岡市）', '&lt;p&gt;&amp;ldquo;関東の清水寺&amp;rdquo;とも言われているのがココ「峰寺山西光院」！&lt;br /&gt;天気がよい日には、霞ヶ浦や筑波山、太平洋までも眺めることができ、その美しい日本ならではの風景に魅了されること間違いなしです。&lt;/p&gt;', 1, '', '234634a91e45-95a6-49a9-adc7-39eeff8b27d9_m.jpg', 2, '2015-09-26 22:39:31', '2015-09-26 22:39:31'),
(20, 'あけのひまわりフェスティバル（筑西市）', '&lt;p&gt;夏の風物詩として親しまれる「あけのひまわりフェスティバル」！毎年8月下旬から9月上旬にかけて開催されており、100万本以上のひまわりやコスモスが咲き誇っている。正面には筑波山を眺めることができ、毎年たくさんの人が訪れる茨城県の人気イベント♪&lt;/p&gt;', 1, '', '2346763df369-d0ff-4608-a373-0a51e3819464_m.jpg', 2, '2015-09-26 22:40:32', '2015-09-26 22:40:32'),
(21, 'シャトーカミヤ / 茨城県牛久市', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;広い庭園でリフレッシュしながら大自然の中でワインを味わえる。&lt;br /&gt;そんなラグジュアリーな空間がシャトーカミヤにはあります。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://find-travel.jp/article/7238&quot; target=&quot;_blank&quot;&gt;find-travel.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;牛久駅の東方に立つレンガ造りの建物。1903（明治36）年神谷傳兵衛氏によって建てられた。シャトー内部にワイン資料館があり、明治・大正時代に使用されたフランス直輸入のワイン・シャンパン醸造機械やワインに関する資料が展示されている。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.jalan.net/kankou/spt_08219ae2180115171/?afCd=&amp;amp;rootCd=&amp;amp;screenId=OUW1221&quot; target=&quot;_blank&quot;&gt;www.jalan.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;100年以上もの歴史のある当時の最先端の記述を用いた本格的なワイン醸造場で、当時の雰囲気に身を委ねながら、ワインをいただくのも粋なものですね。オシャレで素敵な歴史的建造物です。&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem c', 1, '', '12546c6685afc-a3bf-4c93-9732-7af66e528e4b_m.jpg', 8, '2015-09-26 22:42:21', '2015-09-26 22:42:21'),
(22, '太田中学校講堂 / 茨城県常陸太田市', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;ゴシック、ロココ様式を基調とし、当時流行していたスティックスタイル（木骨様式）を取り入れてあり、内部には、校章の掘られた演台やエンタシス柱、コリント風の柱頭飾りなどが施されています。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.jalan.net/kankou/spt_08212ae2180021775/?afCd=&amp;amp;rootCd=&amp;amp;screenId=OUW1221&quot; target=&quot;_blank&quot;&gt;www.jalan.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;この様式の建築物が当時のまま現存しているのは稀少で、当時の建築技術の高さや面影を今に伝える重要な建築物として、昭和51年に国の重要文化財に指定されました。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.kanko-hitachiota.com/wp/hitachiota/leisure/%E5%8F%B2%E8%B7%A1/%E5%A4%AA%E7%94%B0%E4%B8%80%E9%AB%98%E8%AC%9B%E5%A0%82/&quot; target=&quot;_blank&quot;&gt;www.kanko-hitachiota.com&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;明治37年に建築された中学校。当時流行りの様式で建てられているだけあって、すごくレトロでオシャレですよね', 1, '', '12546dbba9fa1-ba58-40e5-bccd-e804efdbe3ad_m.jpg', 1, '2015-09-26 22:42:55', '2015-09-26 22:42:55'),
(23, '旧上岡小学校 / 茨城県久慈郡', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;たくさんのドラマや映画の舞台となっている旧上岡小学校は明治時代に建てられた木造校舎で、古き良き時代の懐かしい雰囲気が今も大切に守られています。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.daigo-kanko.jp/?page_id=4440&quot; target=&quot;_blank&quot;&gt;www.daigo-kanko.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;ＮＨＫ朝の連続ドラマ「おひさま」で、　主演の井上真央さんが演じるヒロイン須藤陽子の母校で赴任先でもある有明山国民学校(有明山尋常小学校)は、この校舎を使っています。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://blogs.yahoo.co.jp/tennnennkozi/62889715.html&quot; target=&quot;_blank&quot;&gt;blogs.yahoo.co.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;明治12年4月20日に創立されたこの歴史的建造物は、平成13年3月31日までは現役の小学校だったようです。現在はドラマのロケ地として使われたりしているレトロで素敵な建物ですので、ドラマファンは是非訪れてみたい場所ですね。&lt;/div&gt;\r\n&lt;div class=', 1, '', '12546fee4caa9-5235-468e-9431-2faf855c90d6_m.jpg', 8, '2015-09-26 22:44:35', '2015-09-26 22:44:35'),
(24, 'なかよしキャンプグラウンド【常陸大宮市】', '&lt;div class=&quot;expImg expItem clearfix &quot;&gt;\r\n&lt;div class=&quot;imageDetail&quot;&gt;\r\n&lt;p class=&quot;comment clearfix&quot;&gt;JR常陸大宮駅より車で20分！茨城県に佇む自然の中にある子供に人気の宿泊施設です。&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;デイキャンプだと大変お手頃価格でお借りすることができます。耳を澄まして自然の音を堪能してきました。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.ibaraki-outdoor.jp/spots/%E3%81%AA%E3%81%8B%E3%82%88%E3%81%97%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E3%82%B0%E3%83%A9%E3%82%A6%E3%83%B3%E3%83%89-2/&quot; target=&quot;_blank&quot;&gt;www.ibaraki-outdoor.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;万一、バーベキューをするのに忘れ物があっても必要なものをレンタルできるので安心です。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.ibaraki-outdoor.jp/spots/%E3%81%AA%E3%81%8B%E3%82%88%E3%81%97%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E3%82%B', 1, '', '11969ec35a4b6-0286-4e9b-b6f0-65971e8c4454_m.jpg', 10, '2015-09-26 22:45:58', '2015-09-26 22:45:58'),
(25, 'オークラフロンティアホテルつくば【つくば市】', '&lt;div class=&quot;expImg expItem clearfix &quot;&gt;\r\n&lt;div class=&quot;imageDetail&quot;&gt;\r\n&lt;p class=&quot;comment clearfix&quot;&gt;茨城県・常磐自動車道桜土浦ICから約15分！小さな子供の宿泊にぴったりなホテルです。&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;急に仕事の疲れを癒したい時、 東京から1時間以内で安く行けて、駅前でのんびり過ごせます。プールもあって、リフレッシュできます。何といっても安価でホテルオークラのサービスを実感できますよ。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.tripadvisor.jp/Hotel_Review-g298167-d301720-Reviews-or10-Okura_Frontier_Hotel_Tsukuba-Tsukuba_Ibaraki_Prefecture_Kanto.html#REVIEWS&quot; target=&quot;_blank&quot;&gt;www.tripadvisor.jp&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;やはり、オークラです。オーバーなサービスなく上品ホテルで好きです。空調が調節できないけれど、不思議に快眠できました。スタックの気配りが行き届いたサービスのおかげと感じました。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.tripadvisor.jp/ShowUserReviews-g2', 1, '', '119697d87ce01-39cf-42d4-a604-3d8597cf7668_m.jpg', 10, '2015-09-26 22:46:56', '2015-09-26 22:46:56'),
(26, 'ビアスパークしもつま【下妻市】', '&lt;div class=&quot;expImg expItem clearfix &quot;&gt;\r\n&lt;div class=&quot;imageDetail&quot;&gt;\r\n&lt;p class=&quot;comment clearfix&quot;&gt;子供と一緒に最高の温泉に浸かりませんか？茨城県の下妻駅よりタクシーにて10分の場所に建つ宿泊施設です。&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;温泉施設あり、下妻市の地ビールも堪能出来ます。駐車場も広く、子供も走り廻れるような広場あり、ファミリーで行っても楽しめます。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.jalan.net/kankou/spt_08210ee4592044836/kuchikomi/?screenId=OUW3701&quot; target=&quot;_blank&quot;&gt;www.jalan.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;露天風呂がきれいでおすすめです。土曜日の夕方過ぎに行きましたが、夕焼けから暗くなる雰囲気がすごく素敵です。内湯、洗い場も広くて快適です。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.jalan.net/kankou/spt_08210ee4592044836/kuchikomi/?screenId=OUW3701&quot; target=&quot;_blank&quot;&gt;www.jalan.net&lt;/a&gt;&lt;/span&gt;&lt;/d', 1, '', '11969299eb1c6-056f-4da2-9c6d-de11631b00d8_m.jpg', 10, '2015-09-26 22:48:06', '2015-09-26 22:48:06'),
(27, 'いこいの村涸沼【鉾田市】', '&lt;div class=&quot;expImg expItem clearfix &quot;&gt;\r\n&lt;div class=&quot;imageDetail&quot;&gt;\r\n&lt;p class=&quot;comment clearfix&quot;&gt;茨城県・大洗鹿島線涸沼駅下車より車で数分の場所に佇む子供に最適な宿泊施設です。&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;食事がおいしく、ハーフバイキングで好きなものを食べられとても良かったです。お風呂も広々して温泉の泉質もよかったです。周りは静かで景色も良く、のんびりできて大変満足です。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.yukoyuko.net/0833/kuchikomi/&quot; target=&quot;_blank&quot;&gt;www.yukoyuko.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;お風呂は茶赤色の温泉水ぬるめで涸沼周辺の景色も良く、外の風呂あれば最高の宿泊施設です。夏休み中は合宿が多いので、秋ごろが良い。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.yukoyuko.net/0833/kuchikomi/&quot; target=&quot;_blank&quot;&gt;www.yukoyuko.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;茨城県', 1, '', '119690571eaa6-0d84-4336-9d16-80ed89deb932_m.jpg', 10, '2015-09-26 22:49:04', '2015-09-26 22:49:04'),
(28, 'サーフィン体験｜茨城県東茨城郡', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;ファンタジーアイランドでは、初めてサーフィンに挑戦する方が安心してサーフィンを続けられるように、JPSA公認プロサーファーをはじめとした海を熟知したインストラクターが、海のしくみやサーフィンについてしっかりとお教えします。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://fi-surf.com/&quot; target=&quot;_blank&quot;&gt;fi-surf.com&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;茨城の海に入ってみたいと思って、こちらのショップを選んで大正解。旅行での立ち寄りだったのに、丁寧に教えてもらえて、分かりやすくて、本当に本当に楽しかったです♪&lt;br /&gt;大洗にきてよかった！って思いました。&lt;/p&gt;\r\n&lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;https://www.facebook.com/surfshopfantasyisland&quot; target=&quot;_blank&quot;&gt;www.facebook.com&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;波を巧みに操るサーファーに誰でも一度は憧れたことがあるのではないでしょうか。サーフィンをやってみたいけど、どうすればいいかわからない。そんなあなたにおすすめする初心者にもやさしいサーフィン体験です。&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;ファン', 1, '', '11298253fbb4a-def1-427c-821f-04a8ffb05696_m.jpg', 5, '2015-09-26 22:50:03', '2015-09-26 22:50:03'),
(29, 'バラグライダー｜茨城県石岡市', '&lt;div class=&quot;expImg expItem clearfix &quot;&gt;&lt;br /&gt;\r\n&lt;div class=&quot;imageDetail&quot;&gt;&lt;br /&gt;\r\n&lt;p class=&quot;comment clearfix&quot;&gt;大絶景を肌で感じてみませんか？&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;&lt;br /&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;エアパークＣＯＯの施設は初心者の方にも安心して飛べる緩やかな傾斜の講習場など、ハード面も充実しており、さらに現役のワールドカップ選手をはじめ、日 本のトップパイロットがインストラクターとして親身に安心サポート！楽しいスカイスポーツを是非、一度体験してください！！&lt;/p&gt;\r\n&lt;br /&gt; &lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://sotoasobi.net/activity/paraglider/3/8/12/85&quot; target=&quot;_blank&quot;&gt;sotoasobi.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;&lt;br /&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;ずーっとやってみたかったパラグライダー！！実際にやってみて最高にたのしかったです。きもちよかったです。たくさんのインストラクターさんが私たちの飛ぶのをたすけてくれてありがとうございました。また来たいです！！！！！&lt;/p&gt;\r\n&lt;/div&gt;', 1, '', '11298a68c41ae-e663-4a64-a052-ac6a7e05dd56_m.jpg', 5, '2015-09-26 22:50:43', '2015-09-26 22:58:26'),
(30, 'リューター体験｜茨城県北茨城市', '&lt;div class=&quot;expRef expItem clearfix&quot;&gt;&lt;br /&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;太平洋を一望できる眺望のよい場所にあり、約700平方メートルのドーム型の建物の中に700度に上るガラス炉を設け、ガラス工芸家による指導を受け吹きガラスづくり、バーナワークが体験できます。またギャラリーにはガラス製品も展示されてます。&lt;/p&gt;\r\n&lt;br /&gt; &lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.jalan.net/kankou/spt_08215aj2200024695/&quot; target=&quot;_blank&quot;&gt;www.jalan.net&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;div class=&quot;expRef expItem clearfix&quot;&gt;&lt;br /&gt;\r\n&lt;p class=&quot;refItem clearfix&quot;&gt;切削工具である、ハンドグラインダーを使用してガラスの表面に文様を掘る技法です。&lt;br /&gt; オリジナルデザインのコップを制作できます。&lt;/p&gt;\r\n&lt;br /&gt; &lt;span class=&quot;clearfix&quot;&gt; 出典：&lt;a href=&quot;http://www.studiosilica.com/experience.leutor.html&quot; target=&quot;_blank&quot;&gt;www.studiosilica.com&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;北茨城が一望できる工房で、ガラスに触れ合うことができるおすすめの施設です。ガラスに自由に絵を描い', 1, '', '1129807ba1837-72e0-4500-a1a9-1d584396e06f_m.jpg', 5, '2015-09-26 22:51:42', '2015-09-26 22:58:05'),
(31, 'あみプレミアムアウトレット', '&lt;div class=&quot;expImg expItem clearfix &quot;&gt;\r\n&lt;div class=&quot;imageDetail&quot;&gt;\r\n&lt;p class=&quot;subTitle clearfix&quot;&gt;あみプレミアムアウトレット&lt;/p&gt;\r\n&lt;p class=&quot;comment clearfix&quot;&gt;茨城で雨でもたのしめる人気の観光スポット第2選はあみプレミアムアウトレットです。晴れていてももちろんおすすめの観光スポットですが、雨の日でも十分楽しめるすばらしい場所です。茨城でもちょっと遠いところにありますので、穴場のアウトレットモールです。&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;茨城でおすすめの観光スポットであるあみプレミアムアウトレットは雨でも楽しめる人気のショッピングモールです。色々なお店もあり、子供から大人まで幅広 い層で楽しめるすてきな場所です。大きな駐車場のため、楽に駐車もできて穴場のスポットでもあります。ぜひ茨城にお越しの際はあみプレミアムアウトレット をお楽しみください。&lt;/div&gt;\r\n&lt;div class=&quot;expText expItem clearfix&quot;&gt;あみプレミアムアウトレット&lt;br /&gt;〒300-1161 　茨城県稲敷郡阿見町よしわら4-1-1 &lt;br /&gt;電話：029-829-5770&lt;br /&gt;＜営業時間＞&lt;br /&gt;10：00～20：00 （季節により変動あり）&lt;br /&gt;休業日 年1回（2月第3木曜日）&lt;br /&gt;駐車場：約3,900台 （無料）&lt;/div&gt;', 1, '', '9404dadc8158-d272-40f1-ad85-41c568ccfcc2_m.jpg', 9, '2015-09-26 22:56:01', '2015-09-26 22:57:09');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`news_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `news`
--
ALTER TABLE `news`
  MODIFY `news_id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=32;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
